# Generated by Django 2.0.13 on 2022-03-02 18:21

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GoodGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_group', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=35)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('article', models.CharField(db_index=True, max_length=20)),
                ('preview_image', models.ImageField(blank=True, upload_to='gallery_products')),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('available', models.BooleanField(default=True)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='barber_app.Categories')),
                ('good_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='goodgroup', to='barber_app.GoodGroups')),
            ],
            options={
                'ordering': ['updated'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/uploads/gallery_products')),
                ('good', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='barber_app.Goods')),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(),
        ),
    ]
