# Generated by Django 2.0.13 on 2022-07-29 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_app', '0004_auto_20220725_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.CharField(choices=[('10.00', '10.00'), ('11.00', '11.00'), ('12.00', '12.00'), ('13.00', '13.00'), ('15.00', '15.00'), ('16.00', '16.00'), ('17.00', '17.00')], max_length=5)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
