# Generated by Django 2.0.13 on 2022-07-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_app', '0005_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.CharField(choices=[('10.00', '10.00'), ('11.00', '11.00'), ('12.00', '12.00'), ('13.00', '13.00'), ('15.00', '15.00'), ('16.00', '16.00'), ('17.00', '17.00')], default='11.00', max_length=5),
        ),
    ]
