# Generated by Django 2.0.13 on 2022-08-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_app', '0006_auto_20220729_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
